// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQYYvwpsa4R-DMDbsl65L6PVOavWyQ7c',
    appId: '1:730334955316:web:2df33afce8bc547ea00761',
    messagingSenderId: '730334955316',
    projectId: 'consultant-21fe8',
    authDomain: 'consultant-21fe8.firebaseapp.com',
    databaseURL: 'https://consultant-21fe8-default-rtdb.firebaseio.com',
    storageBucket: 'consultant-21fe8.appspot.com',
    measurementId: 'G-5FNE85W526',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1w369gQnpv_wYs9vFDjWcynIIr8go1I',
    appId: '1:730334955316:android:0c023213994a0ae6a00761',
    messagingSenderId: '730334955316',
    projectId: 'consultant-21fe8',
    databaseURL: 'https://consultant-21fe8-default-rtdb.firebaseio.com',
    storageBucket: 'consultant-21fe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIAeV1FClYqEx4kFdZmM8T49KtuEF-po',
    appId: '1:730334955316:ios:7b04f79327cfa9cfa00761',
    messagingSenderId: '730334955316',
    projectId: 'consultant-21fe8',
    databaseURL: 'https://consultant-21fe8-default-rtdb.firebaseio.com',
    storageBucket: 'consultant-21fe8.appspot.com',
    iosBundleId: 'com.example.colloboratorFlex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFIAeV1FClYqEx4kFdZmM8T49KtuEF-po',
    appId: '1:730334955316:ios:7b04f79327cfa9cfa00761',
    messagingSenderId: '730334955316',
    projectId: 'consultant-21fe8',
    databaseURL: 'https://consultant-21fe8-default-rtdb.firebaseio.com',
    storageBucket: 'consultant-21fe8.appspot.com',
    iosBundleId: 'com.example.colloboratorFlex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSQYYvwpsa4R-DMDbsl65L6PVOavWyQ7c',
    appId: '1:730334955316:web:d42be2b0587e42cba00761',
    messagingSenderId: '730334955316',
    projectId: 'consultant-21fe8',
    authDomain: 'consultant-21fe8.firebaseapp.com',
    databaseURL: 'https://consultant-21fe8-default-rtdb.firebaseio.com',
    storageBucket: 'consultant-21fe8.appspot.com',
    measurementId: 'G-QXSHQ1YMKS',
  );
}
